version: "3.9"
services:
  db:
    image: postgres:15
    container_name: demo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest:latest
    container_name: demo_postgrest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      PGRST_DB_URI: postgres://postgres:postgrespassword@db:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
      PGRST_SERVER_PORT: 8080
